### ISSUE TITLE
Add opportunity to create vector with more dimension from other vector

### ISSUE THREAD

**Issue by VlasovRoman** [dexset/descore#12]
Like
auto vec = vec2(2, 3);
auto newVec = vec3(vec);

**Comment by deviator** [comment]
It's a protection mechanism borrowed from GLSL.
In most cases (in 3D graphics), when creating vec4 from vec3, fourth component of result vector (w) must containt 1.0 (gomogeneous coordinates), but if we allows creating vec4 from vec3 directly it can make a mess.
for example:
```d
mat4 m = someTransformMatrix();
auto a = vec3(1,2,3);
auto b = ( m * vec4(a,1) ).xyz; // true result for point transform (with offset)
auto c = ( m * vec4(a,0) ).xyz; // true result for vector transform (without offset)
auto c = ( m * vec4(a) ).xyz; // mess
```

What must be in z component of newVec? zero or first component of vec (loop writing vec.x) or 1.0f?
If we create vec4 from vec2 what must be in z and w components?

currently supported creating vector with other dimensions like this:
```d
auto a = vec2(2,3);
auto b = vec3( a, 4 ); // [ 2, 3, 4 ]
auto c = vec4( 0, a.yx, 1 ); // [ 0, 3, 2, 1 ]
auto d = b.xz; // equals d = vec2( b.x, b.z )
auto e = vec4( c.wx, d ); // [ 1, 0, 2, 4 ]
```
and supported creating from one value
```d
auto a = vec3(1); // [ 1, 1, 1 ]
```

**Comment by VlasovRoman** [comment]
Ok, thanks) But i have one question: how i can to increase a vector by number of float/Real and etc? I think, that after your answer you can to close this Issue.

**Comment by deviator** [comment]
if I understood correctly you mean increase number of dimensions.
Vector struct have ability to be dynamic. Matrix can be dynamic too (and half dynamic).
```d
alias vecD = Vector!(0,float); // in vector.d
auto a = vecD( 1, 2, 3, 4, 5 );
auto b = vecD( a, a, 1, 2, 3 );
a = b;
a.length = 23; 
```
If dimenstion number set to zero `data` field in struct makes by `static if` as dynamic array.
It imposes limitations (no access by symbols, like `a.xyz`, no direct copy arrays of vector, etc).
We (who develop this lib) have considered idea of static increase, but decided that the dynamic vectors are close problem (in big dimensions dynamic vectors creates faster).
We rarely use this ability (I use it ones for method of least squares), therefore it can have bugs. If you find these bugs please open issue here.
